-- Add down migration script here
DROP SCHEMA IF EXISTS game CASCADE;
DROP SCHEMA IF EXISTS resources CASCADE;
DROP SCHEMA IF EXISTS terrain CASCADE;
DROP SCHEMA IF EXISTS buildings CASCADE;
DROP SCHEMA IF EXISTS actions CASCADE;