-- Revert all schemas

DROP SCHEMA IF EXISTS actions CASCADE;
DROP SCHEMA IF EXISTS buildings CASCADE;
DROP SCHEMA IF EXISTS terrain CASCADE;
DROP SCHEMA IF EXISTS resources CASCADE;
DROP SCHEMA IF EXISTS game CASCADE;
