[alias]
clear = "run --release --bin server -- --clear --map=Gaulyia"
generate = "run --release --bin server -- --generate-world --map=Gaulyia"
globals = "run --release --bin server -- --generate-globals --map=Gaulyia"
server = "run --release --bin server -- --map=Gaulyia"
server-ymir = "run --release --bin server -- --map=seed42_2048"
clear-ymir = "run --release --bin server -- --clear --map=seed42_2048"
globals-ymir = "run --release --bin server -- --generate-globals --map=seed42_2048"
client = "run --release --bin client"